EngineeringThesis/Controllers/ManageMsrtAreasController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using X.PagedList;

namespace EngineeringThesis.Controllers
{
    //[Authorize(Roles = "Admin Panel,Managing Points and Areas")]
    public class ManageMsrtAreasController : Controller
    {
        private readonly IPointAndAreaService _pointAndAreaService;

        private readonly int _pageSize =
            Convert.ToInt32(ConfigurationManager.AppSettings["manageMsrtAreasIndexPageSize"]);

        public ManageMsrtAreasController(IPointAndAreaService pointAndAreaService)
        {
            _pointAndAreaService = pointAndAreaService;
        }

        [HttpGet]
        public ActionResult Index(int page = 1)
        {
            var model = _pointAndAreaService.GetManageAreassViewModels();
            var viewModel = model.ToPagedList(page, _pageSize);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id)
        {
            _pointAndAreaService.DeleteArea(id);
            TempData["message"] = "You succesfully removed area!";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CreateAreaDto model)
        {
            if (ModelState.IsValid)
            {
                _pointAndAreaService.CreateNewArea(model);
                TempData["message"] = "You succesfully created new area!";
                return RedirectToAction("Index");
            }
            var invalidModel = _pointAndAreaService.GetCreateAreaViewModelFromInvalidModel(model);
            return View(invalidModel);
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            var model = _pointAndAreaService.GetEditAreaViewModel(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(EditAreaDto model)
        {
            if (ModelState.IsValid)
            {
                _pointAndAreaService.UpdateArea(model);
                TempData["message"] = "You succesfully edited area!";
                return RedirectToAction("Index");
            }
            var invalidModel = _pointAndAreaService.GetEditAreaViewModelFromInvalidModel(model);
            return View(invalidModel);
        }

        [HttpGet]
        public ActionResult AssignPoints(string id)
        {
            var model = _pointAndAreaService.GetAssignPointsToAreaViewModel(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AssignPoints(AssignPointsToAreaDto model)
        {
            _pointAndAreaService.AssignPointsToArea(model);
            TempData["message"] = "You succesfully assigned points to area!";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Details(string id)
        {
            var model = _pointAndAreaService.GetAreaDetails(id);
            return View(model);
        }
    }
}

EngineeringThesis/Views/ManageMsrtAreas/AssignPoints.cshtml
@using EngineeringThesis.Resources
@model EngineeringThesis.Controllers.AssignPointsToAreaViewModel
@{
    ViewBag.Title = BackEndResources.ManageArea_AssignPoints_AssignPointsTo + @Model.Name + "'s" + BackEndResources.ManageArea_AssignPoints_area;
}

<h2>@BackEndResources.ManageArea_AssignPoints_AssignPointsTo @Model.Name's @BackEndResources.ManageArea_AssignPoints_area </h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => Model.Id)
    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            @Html.Label("Points:", new { @class = "control-label col-md-2" })
            <span class="col-md-10">
                @foreach (var item in Model.Points)
                {
                    <span class="col-md-4">
                        <label class="col-md-12">
                            <input type="checkbox" name="SelectedPoints" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                            @item.Text
                        </label>
                    </span>
                }
            </span>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-5 col-md-7">
                <a href="@Url.Action("Index")" class="btn btn-default">@BackEndResources.ManageArea_AssignPoints_BackToList</a>
                <input type="submit" value="@BackEndResources.ManageArea_AssignPoints_Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

EngineeringThesis/Views/ManageMsrtAreas/Create.cshtml
@using EngineeringThesis.Resources
@model EngineeringThesis.Controllers.CreateAreaViewModel

@{
    ViewBag.Title = "Create";
}

<br />
@using (Html.BeginForm("Create", "ManageMsrtAreas", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>@BackEndResources.ManageMsrtAreas_Create_Title</h4>
    <hr />
    <div class="form-group">
        <label class="col-xs-2 control-label">
            @BackEndResources.ManageMsrtAreas_Create_Name
        </label>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label class="col-xs-2 control-label">
            @BackEndResources.ManageMsrtAreas_Create_Description
        </label>
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Description, new {@class = "form-control no-resize", @rows = "6"})
            @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <a href="@Url.Action("Index")" class="btn btn-default">@BackEndResources.ManageMsrtArea_Create_BackToList</a>
            <input type="submit" value="@BackEndResources.ManageMsrtArea_Create_Create" class="btn btn-success" />
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EngineeringThesis/Views/ManageMsrtAreas/Details.cshtml
@using EngineeringThesis.Resources
@model EngineeringThesis.Models.AreaDetailsViewModel

@{
    ViewBag.Title = @BackEndResources.ManageArea_Details_DetailsOf + " " + Model.Name + "'s " + BackEndResources.ManageArea_Details_area;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@BackEndResources.ManageArea_Details_DetailsOf @Model.Name's @BackEndResources.ManageArea_Details_area</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @BackEndResources.ManageArea_Details_AreaName
        </dt>
        <dd>
            @Model.Name
        </dd>
        <br />
        <dt>
            @BackEndResources.ManageArea_Details_AreaDescription
        </dt>
        <dd>
            @Model.Description
        </dd>
        <br />
        <dt>
            @BackEndResources.ManageArea_Details_PointsAssigned
        </dt>
        <dd>
            @if (Model.Points.Count == 0)
            {
                @BackEndResources.ManageArea_Details_NoPointsAssigned
            }
            @foreach (var point in Model.Points)
            {
                @point.Name
                <br />
            }
        </dd>
    </dl>
</div>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        @Html.ActionLink(BackEndResources.ManageArea_Details_BackToList, "Index", null, new { @class = "btn btn-default" })
        @Html.ActionLink(BackEndResources.ManageArea_Details_Edit, "Edit", new {id = Model.Id}, new {@class = "btn btn-default"})
        </div>
    <br />
</div>
<hr />

EngineeringThesis/Views/ManageMsrtAreas/Edit.cshtml
@using EngineeringThesis.Resources
@model EngineeringThesis.Models.EditAreaViewModel

@{
    ViewBag.Title = "Edit";
}


<h2>Edit @Model.Name area.</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            <label class="col-xs-2 control-label">
                @BackEndResources.ManageMsrtAreas_Edit_Name
            </label> <div class="col-md-10">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-2 control-label">
                @BackEndResources.ManageMsrtAreas_Edit_Description
            </label>  <div class="col-md-10">
                @Html.TextAreaFor(m => m.Description, new { @class = "form-control no-resize", @rows = 6 })
                @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="@Url.Action("Index")" class="btn btn-default">@BackEndResources.ManageMsrtArea_Edit_BackToList</a>
                <input type="submit" value="@BackEndResources.ManageMsrtArea_Edit_Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EngineeringThesis/Views/ManageMsrtAreas/Index.cshtml
@using EngineeringThesis.Resources
@using X.PagedList
@using X.PagedList.Mvc
@model IEnumerable<EngineeringThesis.Controllers.ManageAreasViewModel>

@{
    ViewBag.Title = @BackEndResources.ManageMsrtAreas_Index_ListOfAreas;
}
<h3 class="tempdata-message">@TempData["message"]</h3>
<h2>@BackEndResources.ManageMsrtAreas_Index_ListOfAreas:</h2>
@Html.ActionLink(BackEndResources.ManageMsrtAreas_Index_CreateNewArea, "Create")

<table class="table">
    <hr />
    <tr>
        <th class="col-md-2">
            @BackEndResources.ManageMsrtAreas_Index_AreaName
        </th>
        <th class="col-md-3">
            @BackEndResources.ManageMsrtAreas_Index_Description
        </th>
        <th class="col-md-2">
            @BackEndResources.ManageMsrtAreas_Index_PointsAssigned
        </th>
        <th class="col-md-5">
            @BackEndResources.ManageMsrtAreas_Index_Actions
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @if (item.Points.Count == 0)
                {
                    @BackEndResources.ManageMsrtAreas_Index_NoPoints
                }
                @foreach (var area in item.Points)
                {
                    <text> @area.Name </text>
                    <br />
                }
            </td>
            <td>
                @Html.ActionLink(BackEndResources.ManageMsrtAreas_Index_Edit, "Edit", "ManageMsrtAreas", new { id = item.Id }, new { @class = "btn btn-default" })
                @Html.ActionLink(BackEndResources.ManageMsrtAreas_Index_AssignPoints, "AssignPoints", "ManageMsrtAreas", new { id = item.Id }, new { @class = "btn btn-default" })
                @Html.ActionLink(BackEndResources.ManageMsrtAreas_Index_Details, "Details", "ManageMsrtAreas", new { id = item.Id }, new { @class = "btn btn-default" })
                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#delete-modal-@(item.Id)">@BackEndResources.ManageMsrtAreas_Index_Delete</button>
            </td>
        </tr>
        <div id="delete-modal-@(item.Id)" class="modal fade">
            <div class="delete-modal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body">
                            <div class="delete-text">
                                @BackEndResources.ManageMsrtAreas_Index_AreYouSure
                            </div>
                            <br />
                            <div class="delete-text-name">
                                @(item.Name.Count() > 30 ? item.Name.Substring(0, 30) + "..." : item.Name)?
                            </div>
                            @using (Html.BeginForm("Delete", "ManageMsrtAreas", new { id = item.Id }))
                            {
                                @Html.AntiForgeryToken()
                                <button class="btn btn-md btn-default" data-dismiss="modal">@BackEndResources.ManageMsrtAreas_Index_Cancel</button>
                                <button type="submit" class="btn btn-md btn-default">@BackEndResources.ManageMsrtAreas_Index_Delete</button>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</table>


<div class="col-xs-12 pager">
    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page = page }))
    <hr />
</div>