EngineeringThesis/Models/ManageUsersViewModel.cs
using System.Collections.Generic;

namespace EngineeringThesis.Services
{
    public class ManageUsersViewModel
    {
        public string Id { get; set; }
        public string Username { get; set; }
        public string FullName { get; set; }
        public List<string> GroupsList { get; set; }
    }
}

EngineeringThesis/Controllers/ManageUsersController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EngineeringThesis.Resources;
using EngineeringThesis.Services;
using X.PagedList;

namespace EngineeringThesis.Controllers
{
    //[Authorize(Roles = "Admin Panel")]
    public class ManageUsersController : Controller
    {
        private readonly IAdminService _adminService;
        private readonly int usersOnSite = Convert.ToInt32(ConfigurationManager.AppSettings["manageUsersIndexPageSize"]);

        public ManageUsersController(IAdminService adminService)
        {
            _adminService = adminService;
        }

        [HttpGet]
        public ActionResult Index(int page = 1)
        {
            var list = _adminService.GetUsersListToShow();
            var model = list.ToPagedList(page, usersOnSite);
            return View(model);
        }

        [HttpGet]
        public ActionResult Details(string id)
        {
            var model = _adminService.GetUserDetails(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(string id)
        {
            _adminService.DeleteUser(id);
            TempData["message"] = "You succesfully removed user account!";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Create()
        {
            var model = _adminService.GetRegisterViewModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RegisterUserByAdminDto model)
        {
            var usernameAlreadyExist = _adminService.CheckIfUsernameAlreadyExist(model.Username);
            if (usernameAlreadyExist)
            {
                ModelState.AddModelError("Username", BackEndResources.ValidationMessages_UsernameAlreadyExist);
            }
            var emailAlreadyExist = _adminService.CheckIfEmailAlreadyExist(model.Email);
            if (emailAlreadyExist)
            {
                ModelState.AddModelError("Email", BackEndResources.ValidationMessages_EmailAlreadyExist);
            }
            if (ModelState.IsValid)
            {
                _adminService.CreateNewUser(model);
                TempData["message"] = "You succesfully created new account!";
                return RedirectToAction("Index");
            }
            var viewModel = _adminService.GetRegisterViewModelFromInvalidModel(model);
            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            var model = _adminService.GetEditUserViewModel(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditUserDto model)
        {
            var usernameAlreadyExist = _adminService.CheckIfUsernameAlreadyExistAndNotOwnedByCurrentUser(model.Id, model.Username);
            if (usernameAlreadyExist)
            {
                ModelState.AddModelError("Username", BackEndResources.ValidationMessages_UsernameAlreadyExist);
            }
            if (ModelState.IsValid)
            {
                _adminService.UpdateUser(model);
                TempData["message"] = "Your succesfully edited user account!";
                return RedirectToAction("Index");
            }
            var viewModel = _adminService.GetEditUserViewModelFromInvalidModel(model);
            return View(viewModel);
        }
    }
}

EngineeringThesis/Views/ManageUsers/Create.cshtml
@using EngineeringThesis.Resources
@model EngineeringThesis.Services.RegisterUserByAdminViewModel

@{
    ViewBag.Title = "Create";
}

<br />
@using (Html.BeginForm("Create", "ManageUsers", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4><b>Create a new account.</b></h4>
    <hr />
    <div class="form-group">
        <label class="col-xs-2 control-label">
            @BackEndResources.ManageUsers_Create_Username
        </label>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Username, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Username, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label class="col-xs-2 control-label">
            @BackEndResources.ManageUsers_Create_Email
        </label>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label class="col-xs-2 control-label">
            @BackEndResources.ManageUsers_Create_FullName
        </label>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.FullName, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.FullName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label class="col-xs-2 control-label">
            @BackEndResources.ManageUsers_Create_Password
        </label>
        <div class="col-md-9">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label class="col-xs-2 control-label">
            @BackEndResources.ManageUsers_Create_ConfirmPassword
        </label>
        <div class="col-md-9">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.ConfirmPassword, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">
            @BackEndResources.ManageUsers_Create_SelectUserGroups
        </label>
        <div class="col-md-10">
            @foreach (var item in Model.GroupsList)
            {
                <label class="col-md-12">
                    <input type="checkbox" name="selectedGroups" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                    @item.Text
                </label>
            }
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <a href="@Url.Action("Index")" class="btn btn-default">@BackEndResources.ManageUsers_Create_BackToList</a>
            <input type="submit" value="@BackEndResources.ManageUsers_Create_Create" class="btn btn-success" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EngineeringThesis/Views/ManageUsers/Details.cshtml
@using EngineeringThesis.Resources
@model EngineeringThesis.Services.UserDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<h2>@BackEndResources.ManageUsers_Details_DetailsOf @Model.Username's @BackEndResources.ManageUsers_Details_account</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @BackEndResources.ManageUsers_Details_Username
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>
        <br />
        <dt>
            @BackEndResources.ManageUsers_Details_FullName
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <br />
        <dt>
            @BackEndResources.ManageUsers_Details_Email
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <br />
        <dt>
            @BackEndResources.ManageUsers_Details_ListOfGroups
        </dt>
        <dd>
            @if (Model.GroupsList.Count == 0)
            {
                @BackEndResources.ManageUsers_Details_NoGroups
            }
            @foreach (var item in Model.GroupsList)
            {
                @item <br />
            }
        </dd>
    </dl>
</div>

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        @Html.ActionLink(BackEndResources.ManageUsers_Details_BackToList, "Index", null, new { @class = "btn btn-default" })
        @Html.ActionLink(BackEndResources.ManageUsers_Details_Edit, "Edit", new { id = Model.Id }, new { @class = "btn btn-default" })
    </div>
    <br />
</div>
<hr />

EngineeringThesis/Views/ManageUsers/Edit.cshtml
@using EngineeringThesis.Resources
@model EngineeringThesis.Services.EditUserViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>@BackEndResources.ManageUsers_Edit_Edit @Model.Username @BackEndResources.ManageUsers_Edit_account</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <label class="col-xs-2 control-label">
                @BackEndResources.ManageUsers_Edit_Username
            </label> <div class="col-md-10">
                @Html.TextBoxFor(m => m.Username, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-2 control-label">
                @BackEndResources.ManageUsers_Edit_Email
            </label> <div class="col-md-10">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-2 control-label">
                @BackEndResources.ManageUsers_Edit_FullName
            </label>
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.FullName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-2 control-label">
               @BackEndResources.ManageUsers_Edit_SelectUserGroups
            </label>
            <span class=" col-md-10">
                @foreach (var item in Model.GroupsList)
                {
                    <label class="col-md-12">
                        <input type="checkbox" name="SelectedGroups" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                        @item.Text
                    </label>
                }
            </span>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="@Url.Action("Index")" class="btn btn-default">@BackEndResources.ManageUsers_Edit_BackToList</a>
                <input type="submit" value="@BackEndResources.ManageUsers_Edit_Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EngineeringThesis/Views/ManageUsers/Index.cshtml
@using EngineeringThesis.Resources
@using X.PagedList
@using X.PagedList.Mvc
@model IEnumerable<EngineeringThesis.Services.ManageUsersViewModel>

@{
    ViewBag.Title = "Index";
}
<h3 class="tempdata-message">@TempData["message"]</h3>
<h2>List of users:</h2>
<p>
    @Html.ActionLink("Create new user", "Create")
</p>
<table class="table">
    <tr>
        <hr />
        <th>
            @BackEndResources.ManageUsers_Index_UserName
        </th>
        <th>
            @BackEndResources.ManageUsers_Index_FullName
        </th>
        <th>
            @BackEndResources.ManageUsers_Index_ActualGroups
        </th>
        <th>
            @BackEndResources.ManageUsers_Index_Actions
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @if (item.GroupsList.Count == 0)
                {
                    @BackEndResources.ManageUsers_Index_NoGroups
                }
                @foreach (var group in item.GroupsList)
                {
                    <text> @group </text>
                    <br />
                }
            </td>
            <td>
                @Html.ActionLink(BackEndResources.ManageUsers_Index_Edit, "Edit", "ManageUsers", new { id = item.Id }, new { @class = "btn btn-default" })
                @Html.ActionLink(BackEndResources.ManageUsers_Index_Details, "Details", "ManageUsers", new { id = item.Id }, new { @class = "btn btn-default" })
                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#delete-modal-@(item.Id)">@BackEndResources.ManageUsers_Index_Delete</button>
            </td>
        </tr>
        <div id="delete-modal-@(item.Id)" class="modal fade">
            <div class="delete-modal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body">
                            <div class="delete-text">
                                @BackEndResources.ManageUsers_Index_AreYouSure
                            </div>
                            <br />
                            <div class="delete-text-name">
                                @(item.Username.Count() > 30 ? item.Username.Substring(0, 30) + "..." : item.Username)?
                            </div>
                            @using (Html.BeginForm("Delete", "ManageUsers", new { id = item.Id }))
                            {
                                @Html.AntiForgeryToken()
                                <button class="btn btn-md btn-default" data-dismiss="modal">Cancel</button>
                                <button type="submit" class="btn btn-md btn-default">Delete</button>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

</table>
<center>
    @Html.PagedListPager((IPagedList)Model, generatePageUrl: page => Url.Action("Index", new { page = page }))
</center>