EngineeringThesis/Controllers/ManageMsrtPointsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using X.PagedList;

namespace EngineeringThesis.Controllers
{
    //[Authorize(Roles = "Admin Panel,Managing Points and Areas")]
    public class ManageMsrtPointsController : Controller
    {
        private readonly IPointAndAreaService _pointAndAreaService;
        private readonly int _pageSize = Convert.ToInt32(ConfigurationManager.AppSettings["manageMsrtPointsIndexPageSize"]);

        public ManageMsrtPointsController(IPointAndAreaService pointAndAreaService)
        {
            _pointAndAreaService = pointAndAreaService;
        }

        [HttpGet]
        public ActionResult Index(int page = 1)
        {
            var model = _pointAndAreaService.GetManagePointsViewModels();
            var viewModel = model.ToPagedList(page, _pageSize);
            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Details(string id)
        {
            var model = _pointAndAreaService.GetPointDetails(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id)
        {
            _pointAndAreaService.DeletePoint(id);
            TempData["message"] = "You succesfully removed point!";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Create()
        {
            var model = _pointAndAreaService.GetCreatePointViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(CreatePointDto model)
        {
            if (ModelState.IsValid)
            {
                _pointAndAreaService.CreateNewPoint(model);
                TempData["message"] = "You succesfully created new point!";
                return RedirectToAction("Index");
            }
            var invalidModel = _pointAndAreaService.GetCreatePointViewModelFromInvalidModel(model);
            return View(invalidModel);
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            var model = _pointAndAreaService.GetEditPointViewModel(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(EditPointDto model)
        {
            if (ModelState.IsValid)
            {
                _pointAndAreaService.UpdatePoint(model);
                TempData["message"] = "You succesfully edited point!";
                return RedirectToAction("Index");
            }
            var invalidModel = _pointAndAreaService.GetEditPointViewModelFromInvalidModel(model);
            return View(invalidModel);
        }
    }
}

EngineeringThesis/Views/ManageMsrtPoints/Create.cshtml
@using EngineeringThesis.Resources
@model EngineeringThesis.Controllers.CreatePointViewModel

@{
    ViewBag.Title = BackEndResources.ManageMsrtPoint_Create_CreateNewPoint;
}

<br />
@using (Html.BeginForm("Create", "ManageMsrtPoints", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>@BackEndResources.ManageMsrtPoint_Create_CreateNewPoint</h4>
    <h5>@BackEndResources.ManageMsrtPoint_Create_Instruction</h5>
    <hr />
    <div class="col-xs-5">
        <div class="form-group">
            <label class="col-xs-3 control-label">
                @BackEndResources.ManageMsrtPoint_Create_Name
            </label>
            <div class="col-md-9">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-3 control-label">
                @BackEndResources.ManageMsrtPoint_Create_Description
            </label>
            <div class="col-md-9">
                @Html.TextAreaFor(m => m.Description, new { @class = "form-control", @rows = "6" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-3 control-label">
                @BackEndResources.ManageMsrtPoint_Create_Localization
            </label>
            <div class="col-md-9">
                @Html.EditorFor(model => model.Localization, new { htmlAttributes = new { @class = "form-control create-view-field", id = "address" } })
                @Html.ValidationMessageFor(model => model.Localization, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Latitude)
                @Html.HiddenFor(model => model.Longitude)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-4 col-md-8">
                <br />
                <a href="@Url.Action("Index")" class="btn btn-default">@BackEndResources.ManageMsrtPoint_Create_BackToList</a>
                <input type="submit" value="@BackEndResources.ManageMsrtPoint_Create_Create" class="btn btn-success" />
            </div>
        </div>
    </div>
    <div class="col-xs-7">
        <div class="form-group">
            <div id="map" class="create-edit-point-map"></div>
        </div>
    </div>
    <div class="col-md-12">
        <hr />
    </div>
}



@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDL0_4zsY1gddcs3kdN3ascv8LEa5Ocz5E&callback=initMap&libraries=places">
    </script>
    <script>
        var Latitude;
        var Longitude;
        var marker;
        var map;

        function initMap() {
            map = new google.maps.Map(document.getElementById('map'),
               {
                   maxZoom: 14,
                   center: { lat: 51.109454, lng: 17.058171000000016 }
               });
            Logic(map);
           }

        function Logic(map) {
            RevertGeocoding(map);
            autocompleteFunc(map);
        }


        function autocompleteFunc(map) {
            var autocomplete = new google.maps.places.Autocomplete(document.getElementById("address"))
            $("#address").attr("placeholder", "Type a Location");
            var geocoder = new google.maps.Geocoder();
            autocomplete.addListener('place_changed', function () {
                var place = autocomplete.getPlace();
                geocodeAddress(geocoder, map)
            })
        }

        function sendLonLat(lat, long) {
            document.getElementById('Latitude').value = lat;
            document.getElementById('Longitude').value = long;
        }

        function RevertGeocoding(map) {
            if (@Model.Latitude != 0 && @Model.Longitude != 0) {
                var geocoder = new google.maps.Geocoder;
                var latlng = { lat: @Model.Latitude, lng: @Model.Longitude };
                geocoder.geocode({ 'location': latlng },
                    function(results, status) {
                        if (status === google.maps.GeocoderStatus.OK) {
                            if (results[1]) {
                                map.setZoom(21);
                                if (!marker) {
                                    marker = new google.maps.Marker({
                                        map: map,
                                        position: latlng,
                                        animation: google.maps.Animation.DROP
                                    })
                                    marker.setMap(map);
                                    marker.setDraggable(true);
                                } else {
                                    marker.setPosition(latlng);
                                }

                                google.maps.event.addListener(marker,
                                    'dragend',
                                    function(event) {
                                        var point = marker.getPosition();
                                        map.panTo(point);
                                        Latitude = point.lat();
                                        Longitude = point.lng();
                                        latlng = { lat: Latitude, lng: Longitude };
                                        sendLonLat(latlng.lat, latlng.lng);
                                        var fastName;
                                        geocoder.geocode({ 'location': latlng },
                                            function(results, status) {
                                                fastName = results[0].formatted_address;
                                                document.getElementById('address').value = fastName;
                                            });
                                    });
                                sendLonLat(latlng.lat, latlng.lng);
                                map.setCenter(results[0].geometry.location);
                            }
                        }
                    });
                return true;
            }
        }


        function geocodeAddress(geocoder, map) {
            var geocoder = new google.maps.Geocoder();
            var address = document.getElementById('address').value;
            geocoder.geocode({ 'address': address }, function (results, status) {
                map.setCenter(results[0].geometry.location);
                boundMapGeocoder(results, map);
                markerMap(results, map)
            });
        }

        function markerMap(results, resultsMap) {
            Latitude = results[0].geometry.location.lat(),
            Longitude = results[0].geometry.location.lng(),
            myLatLng = { lat: Latitude, lng: Longitude };
            if (!marker) {
                marker = new google.maps.Marker({
                    map: resultsMap,
                    position: myLatLng,
                    animation: google.maps.Animation.DROP
                })
                marker.setMap(resultsMap);
                marker.setDraggable(true);
            } else {
                marker.setPosition(myLatLng);
            }

            google.maps.event.addListener(marker, 'dragend', function (event) {
                var point = marker.getPosition();
                resultsMap.panTo(point);
                Latitude = point.lat();
                Longitude = point.lng();
                myLatLng = { lat: Latitude, lng: Longitude };
                sendLonLat(myLatLng.lat, myLatLng.lng);
            });
            sendLonLat(myLatLng.lat, myLatLng.lng);
        }

        function boundMapGeocoder(results, resultsMap) {
            var bounds = new google.maps.LatLngBounds();
            loc = new google.maps.LatLng(results[0].geometry.location.lat(), results[0].geometry.location.lng());
            bounds.extend(loc);
            resultsMap.fitBounds(bounds);
            resultsMap.panToBounds(bounds);
        }

    </script>
}

EngineeringThesis/Views/ManageMsrtPoints/Details.cshtml
@using EngineeringThesis.Resources
@model EngineeringThesis.Controllers.PointDetailsViewModel

@{
    ViewBag.Title = @BackEndResources.ManageMsrtPoint_Details_DetailsOf + " " + Model.Name + "'s " + BackEndResources.ManageMsrtPoint_Details_point;
}

<h2>@BackEndResources.ManageMsrtPoint_Details_DetailsOf  @Model.Name's @BackEndResources.ManageMsrtPoint_Details_point</h2>

<div class="point-details-container">
    <hr />
    <div class="col-xs-4">
        <br />
        <br />
        <div>
            <b> @BackEndResources.ManageMsrtPoint_Details_PointName</b>
            @Html.DisplayFor(model => model.Name)
        </div>
        <br />
        <div>
            <b>
                @BackEndResources.ManageMsrtPoint_Details_Description
            </b>
            @Html.DisplayFor(model => model.Description)
        </div>
        <br />
        <div>
            <b>
                @BackEndResources.ManageMsrtPoint_Details_Latitude
            </b>
            @Html.DisplayFor(model => model.Latitude)
        </div>
        <br />
        <div>
            <b>
                @BackEndResources.ManageMsrtPoint_Details_Longitude
            </b>
            @Html.DisplayFor(model => model.Longitude)
        </div>
        <br />
        <div>
            <b>
                @BackEndResources.ManageMsrtPoint_Details_Address
            </b>
            @Html.DisplayFor(model => model.Localization)
        </div>
        <br />
        <div>
            <b>
                @BackEndResources.ManageMsrtPoint_Details_AssignedToAreas
            </b>
            @if (Model.Areas.Count == 0)
            {
                <p>@BackEndResources.ManageMsrtPoint_Details_NoAreas</p>
            }
            @foreach (var item in Model.Areas)
            {
                @item.Name
                <br/>
            }
        </div>
        <br/>
        <div class="form-group">
            <div class="col-md-offset-1 col-md-10">
                @Html.ActionLink(BackEndResources.ManageMsrtPoint_Details_BackToList, "Index", null, new { @class = "btn btn-default" })
                @Html.ActionLink(BackEndResources.ManageMsrtPoint_Details_Edit, "Edit", new { id = Model.Id }, new { @class = "btn btn-default" })
            </div>
            <br />
        </div>
    </div>
    <div class="col-xs-8">
        <div id="googleMap" class="point-details-map"></div>
    </div>
    <div class="col-md-12">
        <br/>
        <hr/>
    </div>
</div>




@section Scripts {
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDL0_4zsY1gddcs3kdN3ascv8LEa5Ocz5E"></script>
    <script>
        var myCenter = new google.maps.LatLng(@Model.Latitude, @Model.Longitude);

        function initialize() {
            var mapProp = {
                center: myCenter,
                zoom: 15,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };

            var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);

            var marker = new google.maps.Marker({
                position: myCenter,
            });

            marker.setMap(map);
        }

        google.maps.event.addDomListener(window, 'load', initialize);
    </script>

}

EngineeringThesis/Views/ManageMsrtPoints/Edit.cshtml
@using EngineeringThesis.Resources
@model EngineeringThesis.Controllers.EditPointViewModel

@{
    ViewBag.Title = BackEndResources.ManageMsrtPoint_Edit_Edit + Model.Name+"'s" + BackEndResources.ManageMsrtPoint_Edit_point;
}
<br />
@using (Html.BeginForm("Edit", "ManageMsrtPoints", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>@BackEndResources.ManageMsrtPoint_Edit_Edit @Model.Name's @BackEndResources.ManageMsrtPoint_Edit_point</h4>
    <h5>@BackEndResources.ManageMsrtPoint_Edit_Instruction</h5>
    <hr />
    <div class="col-xs-5">
        <div class="form-group">
            <label class="col-xs-3 control-label">
                @BackEndResources.ManageMsrtPoint_Edit_Name
            </label>
            <div class="col-md-9">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-3 control-label">
                @BackEndResources.ManageMsrtPoint_Edit_Description
            </label>
            <div class="col-md-9">
                @Html.TextAreaFor(m => m.Description, new { @class = "form-control", @rows = "6" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-3 control-label">
                @BackEndResources.ManageMsrtPoint_Edit_Localization
            </label>
            <div class="col-md-9">
                @Html.EditorFor(model => model.Localization, new { htmlAttributes = new { @class = "form-control create-view-field", id = "address" } })
                @Html.ValidationMessageFor(model => model.Localization, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Latitude)
                @Html.HiddenFor(model => model.Longitude)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-4 col-md-8">
                <br />
                <a href="@Url.Action("Index")" class="btn btn-default">@BackEndResources.ManageMsrtPoint_Edit_BackToList</a>
                <input type="submit" value="@BackEndResources.ManageMsrtPoint_Edit_Save" class="btn btn-success" />
            </div>
        </div>
    </div>
    <div class="col-xs-7">
        <div class="form-group">
            <div id="map" class="create-edit-point-map"></div>
        </div>
    </div>
    <div class="col-md-12">
        <hr />
    </div>
}




@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/_googleMaps.js"></script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDL0_4zsY1gddcs3kdN3ascv8LEa5Ocz5E&callback=initMap&libraries=places">

    </script>
    <script>
        function RevertGeocoding(map) {
            if (@Model.Latitude != 0 && @Model.Longitude != 0) {
                var geocoder = new google.maps.Geocoder;
                var latlng = { lat: @Model.Latitude, lng: @Model.Longitude };
                geocoder.geocode({ 'location': latlng },
                    function(results, status) {
                        if (status === google.maps.GeocoderStatus.OK) {
                            if (results[1]) {
                                map.setZoom(21);
                                if (!marker) {
                                    marker = new google.maps.Marker({
                                        map: map,
                                        position: latlng,
                                        animation: google.maps.Animation.DROP
                                    })
                                    marker.setMap(map);
                                    marker.setDraggable(true);
                                } else {
                                    marker.setPosition(latlng);
                                }

                                google.maps.event.addListener(marker,
                                    'dragend',
                                    function(event) {
                                        var point = marker.getPosition();
                                        map.panTo(point);
                                        Latitude = point.lat();
                                        Longitude = point.lng();
                                        latlng = { lat: Latitude, lng: Longitude };
                                        sendLonLat(latlng.lat, latlng.lng);
                                        var fastName;
                                        geocoder.geocode({ 'location': latlng },
                                            function(results, status) {
                                                fastName = results[0].formatted_address;
                                                document.getElementById('address').value = fastName;
                                            });
                                    });
                                sendLonLat(latlng.lat, latlng.lng);
                                map.setCenter(results[0].geometry.location);
                            }
                        }
                    });
                return true;
            }
        }
    </script>
}

EngineeringThesis/Views/ManageMsrtPoints/Index.cshtml
@using EngineeringThesis.Resources
@using X.PagedList
@using X.PagedList.Mvc
@model IEnumerable<EngineeringThesis.Controllers.ManagePointsViewModel>

@{
    ViewBag.Title = BackEndResources.ManageMsrtPoints_Index_ListOfPoints;
}
<h2>@BackEndResources.ManageMsrtPoints_Index_ListOfPoints:</h2>
<p>
    @Html.ActionLink(BackEndResources.ManageMsrtPoints_Index_CreateNewPoint, "Create")
</p>
<table class="table">
    <hr />
    <tr>
        <th class="col-md-2">
            @BackEndResources.ManageMsrtPoints_Index_PointName
        </th>
        <th class="col-md-2">
            @BackEndResources.ManageMsrtPoints_Index_Longitude
        </th>
        <th class="col-md-2">
            @BackEndResources.ManageMsrtPoints_Index_Latitude
        </th>
        <th class="col-md-2">
            @BackEndResources.ManageMsrtPoints_Index_AssignedToAreas
        </th>
        <th class="col-md-4">
            @BackEndResources.ManageMsrtPoints_Index_Actions
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Longitude)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Latitude)
            </td>
            <td>
                @if (item.Areas.Count == 0)
                {
                    @BackEndResources.ManageMsrtPoints_Index_NoAreas
                }
                @foreach (var area in item.Areas)
                {
                    <text> @area.Name </text>
                    <br />
                }
            </td>
            <td>
                @Html.ActionLink(BackEndResources.ManageMsrtPoints_Index_Edit, "Edit", "ManageMsrtPoints", new { id = item.Id }, new { @class = "btn btn-default" })
                @Html.ActionLink(BackEndResources.ManageMsrtPoints_Index_Details, "Details", "ManageMsrtPoints", new { id = item.Id }, new { @class = "btn btn-default" })
                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#delete-modal-@(item.Id)">@BackEndResources.ManageMsrtPoints_Index_Delete</button>
            </td>
        </tr>
        <div id="delete-modal-@(item.Id)" class="modal fade">
            <div class="delete-modal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body">
                            <div class="delete-text">
                                @BackEndResources.ManageMsrtPoints_Index_AreYouSure
                            </div>
                            <br />
                            <div class="delete-text-name">
                                @(item.Name.Count() > 30 ? item.Name.Substring(0, 30) + "..." : item.Name)?
                            </div>
                            @using (Html.BeginForm("Delete", "ManageMsrtPoints", new { id = item.Id }))
                            {
                                @Html.AntiForgeryToken()
                                <button class="btn btn-md btn-default" data-dismiss="modal">@BackEndResources.ManageMsrtPoints_Index_Cancel</button>
                                <button type="submit" class="btn btn-md btn-default">@BackEndResources.ManageMsrtPoints_Index_Delete</button>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</table>

<div class="col-xs-12 pager">
    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page = page }))
    <hr />
</div>