EngineeringThesis/Controllers/ManageGroupsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EngineeringThesis.Dtos;
using EngineeringThesis.Services;
using X.PagedList;


namespace EngineeringThesis.Controllers
{
    //[Authorize(Roles = "Admin Panel")]
    public class ManageGroupsController : Controller
    {
        private IAdminService _groupService;
        private readonly int pageSize = Convert.ToInt32(ConfigurationManager.AppSettings["manageGroupsIndexPageSize"]);

        public ManageGroupsController(IAdminService groupService)
        {
            _groupService = groupService;
        }

        [HttpGet]
        public ActionResult Index(int page=1)
        {
            var groups = _groupService.GetListOfGroupsWithRoles();
            var pagedList = groups.ToPagedList(page, pageSize);
            return View(pagedList);
        }

        [HttpGet]
        public ActionResult Details(string id)
        {
            var group = _groupService.GetGroupDetails(id);
            return View(group);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id)
        {
            _groupService.DeleteGroup(id);
            TempData["message"] = "You succesfully removed group!";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Create()
        {
            var model = _groupService.GetCreateModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateGroupDto group)
        {
            if (ModelState.IsValid)
            {
                _groupService.CreateGroup(group);
                TempData["message"] = "You succesfully created new group!";
                return RedirectToAction("Index");
            }
            var model = _groupService.GetCreateModel();
            model.GroupName = group.GroupName;
            model.GroupDescription = group.GroupDescription;
            return View(model);

        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            var model = _groupService.GetGroupToEdit(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditGroupDto group)
        {
            if (ModelState.IsValid)
            {
                _groupService.UpdateGroup(group);
                TempData["message"] = "You succesfully edited group!";
                return RedirectToAction("Index");
            }
            var model = _groupService.GetGroupToEdit(group.Id);
            model.GroupName = group.GroupName;
            model.GroupDescription = group.GroupDescription;
            return View(model);

        }

        [HttpGet]
        public ActionResult AssignUsers(string id)
        {
            var model = _groupService.GetAssignUserViewModel(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AssignUsers(AssignUserToGroupDto group)
        {
            _groupService.AssignUsersToGroup(group);
            TempData["message"] = "You succesfully assigned users to group!";
            return RedirectToAction("Index");
        }

    }
}

EngineeringThesis/Views/ManageGroups/AssignUsers.cshtml
@using EngineeringThesis.Resources
@model EngineeringThesis.Services.AssignUserToGroupViewModel

@{
    ViewBag.Title = "Assign Users";
}

<h2>@BackEndResources.ManageGroups_AssignUsers_AssignUsersTo @Model.GroupName's @BackEndResources.ManageGroups_AssignUsers_group</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => Model.Id)
    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            <label class="col-xs-2">
                @BackEndResources.ManageGroups_AssignUsers_Users
            </label>
            <div class="col-md-10">
                @foreach (var item in Model.Users)
                {
                    <div class="col-md-4">
                        <label>
                            <input type="checkbox" name="SelectedUsers" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                            @item.Text
                        </label>
                    </div>
                }
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-5 col-md-7">
                <a href="@Url.Action("Index")" class="btn btn-default">@BackEndResources.ManageGroups_AssignUsers_BackToList</a>
                <input type="submit" value="@BackEndResources.ManageGroups_AssignUsers_Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EngineeringThesis/Views/ManageGroups/Create.cshtml
@using EngineeringThesis.Resources
@model EngineeringThesis.Services.CreateGroupViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
@using (Html.BeginForm("Create", "ManageGroups", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4><b>@BackEndResources.ManageGroups_Create_CreateNewGroup</b></h4>
    <hr />
    <div class="form-group">
        <label class="col-xs-2 control-label">
            @BackEndResources.ManageGroups_Create_GroupName
        </label>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.GroupName, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.GroupName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label class="col-xs-2 control-label">
            @BackEndResources.ManageGroups_Create_CreateDescription
        </label>
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.GroupDescription, new { @class = "form-control", @rows = "6" })
            @Html.ValidationMessageFor(m => m.GroupDescription, "", new { @class = "text-danger" })
        </div>
    </div>
        <div class="form-group">
            <label class="col-xs-2 control-label">
                @BackEndResources.ManageGroups_Create_SelectGroupModules
            </label>
            <div class="col-md-10">
                @foreach (var item in Model.Roles)
                {
                    <label class="col-md-12">
                        <input type="checkbox" name="selectedRoles" value="@item.Value" class="checkbox-inline" />
                        @item.Text
                    </label>
                }
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="@Url.Action("Index")" class="btn btn-default">@BackEndResources.ManageGroups_Create_BackToList</a>
                <input type="submit" value="@BackEndResources.ManageGroups_Create_Create" class="btn btn-success" />
            </div>
        </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EngineeringThesis/Views/ManageGroups/Details.cshtml
@using EngineeringThesis.Resources
@model EngineeringThesis.Models.GroupDetailsViewModel

@{
    ViewBag.Title = @BackEndResources.ManageGroups_Details_DetailsOf + " " + Model.GroupName + "'s " + BackEndResources.ManageGroups_Details_group;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@BackEndResources.ManageGroups_Details_DetailsOf @Model.GroupName's @BackEndResources.ManageGroups_Details_group</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @BackEndResources.ManageGroups_Details_GroupName
        </dt>
        <dd>
            @Model.GroupName
        </dd>
        <br />
        <dt>
            @BackEndResources.ManageGroups_Details_GroupDescription
        </dt>
        <dd>
            @Model.GroupDescription
        </dd>
        <br />
        <dt>
            @BackEndResources.ManageGroups_Details_ModulesAssigned
        </dt>
        <dd>
            @if (Model.Roles.Count == 0)
            {
                @BackEndResources.ManageGroups_Details_NoModulesAssigned
            }
            @foreach (var role in Model.Roles)
            {
                @role
                <br/>
            }
        </dd>
        <br />
        <dt>
            @BackEndResources.ManageGroups_Details_UsersAssigned
        </dt>
        <dd>
            @if (Model.Users.Count == 0)
            {
                @BackEndResources.ManageGroups_Details_NoUsersAssigned
            }
            @foreach (var user in Model.Users)
            {
                @user
                <br />
            }
        </dd>
    </dl>
</div>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        @Html.ActionLink(BackEndResources.ManageGroups_Details_BackToList, "Index", null, new { @class = "btn btn-default" })
        @Html.ActionLink(BackEndResources.ManageGroups_Details_Edit, "Edit", new {id = Model.Id}, new {@class = "btn btn-default"})
    </div>
    <br/>
</div>
<hr/>

EngineeringThesis/Views/ManageGroups/Edit.cshtml
@using EngineeringThesis.Resources
@model EngineeringThesis.Models.EditGroupViewModel

@{
    ViewBag.Title = BackEndResources.ManageGroups_Edit_Edit + " " + Model.GroupName + " " + BackEndResources.ManageGroups_Edit_group;
}

<br />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.HiddenFor(model => model.Id)
        <h4><b>@BackEndResources.ManageGroups_Edit_Edit @Model.GroupName @BackEndResources.ManageGroups_Edit_group</b></h4>
        <hr />
        <div class="form-group">
            <div class="col-md-2 control-label manage-groups-font-weight">
                @BackEndResources.ManageGroups_Edit_GroupName
            </div>
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.GroupName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.GroupName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-2 control-label manage-groups-font-weight">
                @BackEndResources.ManageGroups_Edit_GroupDescription
            </div>
            <div class="col-md-10">
                @Html.TextAreaFor(m => m.GroupDescription, new { @class = "form-control no-resize", @rows = 6 })
                @Html.ValidationMessageFor(m => m.GroupDescription, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-2 control-label manage-groups-font-weight">
                @BackEndResources.ManageGroups_Edit_GroupModules
            </div>
            <span class=" col-md-10">
                @foreach (var item in Model.Roles)
                {
                    <label class="col-md-12">
                        <input type="checkbox" name="SelectedRoles" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                        @item.Text
                    </label>
                }
            </span>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="@Url.Action("Index")" class="btn btn-default">@BackEndResources.ManageGroups_Edit_BackToList</a>
                <input type="submit" value="@BackEndResources.ManageGroups_Edit_Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EngineeringThesis/Views/ManageGroups/Index.cshtml
@model IEnumerable<EngineeringThesis.Models.GroupViewModel>
@using EngineeringThesis.Resources
@using X.PagedList;
@using X.PagedList.Mvc;
@using System.Web.Mvc.Html;

@{
    ViewBag.Title = "Groups Manager";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h3 class="tempdata-message">@TempData["message"]</h3>
<h2>@BackEndResources.ManageGroups_Index_ListOfGroups</h2>
@Html.ActionLink(BackEndResources.ManageGroups_Index_CreateNewGroup, "Create")

<table class="table">
    <hr />
    <thead>
        <tr>
            <th>
                @BackEndResources.ManageGroups_Index_GroupName
            </th>
            <th>
                @BackEndResources.ManageGroups_Index_GroupDescription
            </th>
            <th>
                @BackEndResources.ManageGroups_Index_AssignedModules
            </th>
            <th>
                @BackEndResources.ManageGroups_Index_Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.GroupName
                </td>
                <td>
                    @item.GroupDescription
                </td>
                <td>
                    @if (item.Roles.Count == 0)
                {
                        @BackEndResources.ManageGroups_Index_NoModulesAssigned
                    }
                    @foreach (var role in item.Roles)
                {
                        @role
                        <br />
                    }
                </td>
                <td>
                    <div>
                        @Html.ActionLink(@BackEndResources.ManageGroups_Index_Edit, "Edit", "ManageGroups", new { id = item.Id }, new { @class = "btn btn-default" })
                        @Html.ActionLink(@BackEndResources.ManageGroups_Index_AssignUsers, "AssignUsers", "ManageGroups", new { id = item.Id }, new { @class = "btn btn-default" })
                        @Html.ActionLink(@BackEndResources.ManageGroups_Index_Details, "Details", "ManageGroups", new { id = item.Id }, new { @class = "btn btn-default" })
                        <button type="button" class="btn btn-default" data-toggle="modal" data-target="#delete-modal-@(item.Id)">@BackEndResources.ManageGroups_Index_Delete</button>
                    </div>
                </td>
            </tr>
            <div id="delete-modal-@(item.Id)" class="modal fade">
                <div class="delete-modal">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-body">
                                <div class="delete-text">
                                    @BackEndResources.ManageGroups_Index_AreYouSure
                                </div>
                                <br />
                                <div class="delete-text-name">
                                    @(item.GroupName.Count() > 30 ? item.GroupName.Substring(0, 30) + "..." : item.GroupName)?
                                </div>
                                @using (Html.BeginForm("Delete", "ManageGroups", new { id = item.Id }))
                                {
                                    @Html.AntiForgeryToken()
                                    <button class="btn btn-md btn-default" data-dismiss="modal">@BackEndResources.ManageGroups_Index_Cancel</button>
                                    <button type="submit" class="btn btn-md btn-default">@BackEndResources.ManageGroups_Index_Delete</button>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </tbody>
</table>
<center>
    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page = page }))
</center>